### ISSUE TITLE
Create event emission for Wizard getting, changing role

### ISSUE THREAD

**Issue by daveaneo** [daveaneo/wizardarmy#5]
@MUHAMMAD-AMMAR-TANWEER 

Please add any other details you need, if any.

**Comment by MUHAMMAD-AMMAR-TANWEER** [comment]
Please add event emitter on roleId assignment of an nft so we know that we need to modify that role in database as well.

**Comment by daveaneo** [comment]
Created.
`    event RoleAppointed(uint256 wizardId, uint256 roleId);
`
