### ISSUE TITLE
Create event emission for...

### ISSUE THREAD

**Issue by daveaneo** [daveaneo/wizardarmy#6]
Please put any events, info you need or other extra fields for existing events:
@MUHAMMAD-AMMAR-TANWEER

**Comment by MUHAMMAD-AMMAR-TANWEER** [comment]
Please add timestamps in accept task and event emitter.
Also add timestamp in claim verification . This way user know how much time they have to complete a task and how much time user have to submit verification.

**Comment by daveaneo** [comment]
@MUHAMMAD-AMMAR-TANWEER 
This information should already be included in every event emission. It is has both block and timestamp or just block. And, with block, the timestamp can be queried.
